### ISSUE TITLE
ValueError: Preprocessing cost must be at least 1 but got 0.000000

### ISSUE THREAD

**Issue by MiBu84** [fplll/strategizer#12]
On CentOS 7.2 (Kernel 4.19), gcc 4.9.4 and Python 3.6.7 I followed the installation instructions within the virtual environment. The Code is compiled and I can run the --help and the benchmark (__main__:   fplll :: nodes:   64551456.0, time: 2.2685s, nodes/s:   28455300.7).
But when executing:

python ./strategize.py --max-block-size 40 --threads 2 --samples 128

I receive:

> (fplllstrat) [mburger@localhost strategizer]$ python ./strategize.py --max-block-size 40 --threads 2 --samples 128
> strategizer.mdc: enum nodes per sec:    28479656.2
> __main__: = block size:   3, samples: 128 =
> Traceback (most recent call last):
>   File "./strategize.py", line 318, in <module>
>     dump_filename=args.filename)
>   File "./strategize.py", line 237, in strategize
>     nsamples=nsamples,
>   File "./strategize.py", line 162, in discover_strategy
>     pruning_params = strategizer(callback)
>   File "/home/mburger/Dokumente/strategizer/strategizer/strategizers.py", line 62, in __call__
>     return self.pruning(data)
>   File "/home/mburger/Dokumente/strategizer/strategizer/strategizers.py", line 252, in pruning
>     pruning_ = Pruning.run(radius, overhead,  R, min(1.05*probability, 0.999))
>   File "src/fpylll/fplll/pruner.pyx", line 648, in fpylll.fplll.pruner.prune
> ValueError: Preprocessing cost must be at least 1 but got 0.000000

**Comment by malb** [comment]
I just ran it successfully here in a fresh virtualenv, following the same instructions.

**Comment by MiBu84** [comment]
Thanks.
Any idea what I can try? Or what the error-message wants to say?

**Comment by malb** [comment]
Are you perhaps running on Python 3?

**Comment by MiBu84** [comment]
In the virtual env python --version gives 2.7.5

**Comment by malb** [comment]
Then I'm out of ideas. Sorry.

**Comment by MiBu84** [comment]
Same on a second computer with equivalent Software but different hardware. So problem with CentOS I guess? Or do you have a slightly different python version?

**Comment by MiBu84** [comment]
Tried it on a VM with Ubuntu, gcc7 and Python 2.7.15. There, it works out of the box. On a third machine with CentOS I additionally installed Python 2.7.15 (instead of 2.7.5), and tried gcc5 and gcc7, but still get:

> strategizer.mdc: enum nodes per sec:    18493438.3
> __main__: = block size:   3, samples: 128 =
> Traceback (most recent call last):
>   File "./strategize.py", line 318, in <module>
>     dump_filename=args.filename)
>   File "./strategize.py", line 237, in strategize
>     nsamples=nsamples,
>   File "./strategize.py", line 162, in discover_strategy
>     pruning_params = strategizer(callback)
>   File "/home/mburger/strategizer/strategizer/strategizers.py", line 62, in __call__
>     return self.pruning(data)
>   File "/home/mburger/strategizer/strategizer/strategizers.py", line 252, in pruning
>     pruning_ = Pruning.run(radius, overhead,  R, min(1.05*probability, 0.999))
>   File "src/fpylll/fplll/pruner.pyx", line 648, in fpylll.fplll.pruner.prune
> ValueError: Preprocessing cost must be at least 1 but got 0.000000

I also tested the fplll-executable which is generated from the cloned git and compiled within the strategizer folder. It works, at least for:

`./fplll svpc-e1-d50.txt -a lll -d 0.99`

After the error message above, the program stucks and has to be killed with Contr. + c.
Then, additionally following errors are displayed, inidcating some problem with multiple processes:


_

> ValueError: Preprocessing cost must be at least 1 but got 0.000000
> Process Process-114:
> Process Process-125:
> Process Process-106:
> Process Process-123:
> Process Process-111:
> Process Process-105:
> Process Process-75:
> Process Process-102:
> Traceback (most recent call last):
> Process Process-103:
> Traceback (most recent call last):
> Traceback (most recent call last):
> Process Process-23:
> Process Process-66:
> Process Process-21:
> Process Process-22:
> Traceback (most recent call last):
> Process Process-5:
> Traceback (most recent call last):
> Process Process-16:
> Traceback (most recent call last):
> Traceback (most recent call last):
> Process Process-101:
> Traceback (most recent call last):
>   File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
> Traceback (most recent call last):
> Process Process-98:
>   File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
>   File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
> Traceback (most recent call last):
> Traceback (most recent call last):
> Traceback (most recent call last):
> Traceback (most recent call last):
>   File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
> Traceback (most recent call last):
>   File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
> Traceback (most recent call last):
>   File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
>   File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
> Traceback (most recent call last):
>   File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
>   File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
> (...) Many, many more of the same kind

_

 
So no ideas left.
